### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ufechner7** [tsabelmann/CANalyze.jl#13]
From reading the documentation it is not clear to me if:
- this package is intended to read CAN bus log files, and if yes, which formats are supported
- or if it is intended to talk with a CAN interface directly, and if yes, how

**Comment by tsabelmann** [comment]
The plan is and was that this package can be used to decode and encode data from and maybe into CAN bus log files. The second point you have mentioned is also possible but I do not plan to add it to this repository. Do you know more about implementing a Julia wrapper around C code?

**Comment by ufechner7** [comment]
Yes, I can implement Julia wrappers around C code. But if the first goal is to read CAN bus log files, which data format do you support or do you want to support? I am currently using .csv files from the [kvaser memorator light](https://www.kvaser.com/product/kvaser-memorator-light-hs-v2/).

See also: https://ufechner7.github.io/2022/08/12/filtering-and-browsing-datasets.html

**Comment by tsabelmann** [comment]
To be honest, currently this package has functionality for analyzing arbitrary CAN bus data using signals and messages, derived from the implementation of PEAK sym files. However, as of now this package does not support any data format. I want to support the candump format because I found it to be very flexible and simple to implement. Are you bound to use Julia for your data analysis?
